controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::index

tools:
    path: /tools
    controller: App\Controller\ToolsController::index

adminTour:
    path: /adminTour
    controller: App\Controller\TourController::adminIndex