controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /home
    controller: App\Controller\HomeController::index

login:
    path: /login
    controller: App\Controller\SecurityController::index

tools:
    path: /tools
    controller: App\Controller\ToolsController::index

adminTour:
    path: /adminTour
    controller: App\Controller\TourController::adminIndex

tour:
    path: /tour
    controller: App\Controller\TourController::index

adminGallery:
    path: /adminGallery
    controller: App\Controller\GalleryController::adminIndex

detailThanks:
    path: /detailThanks
    controller: App\Controller\DetailController::detailThanks

adminTourRequest:
    path: /adminTourRequest
    controller: App\Controller\TourRequestController::adminIndex

contact:
    path: /contact
    controller: App\Controller\ContactController::index

contactThanks:
    path: /contactThanks
    controller: App\Controller\ContactController::contactThanks